(ns genetic-byte-beats.forms.evolved)

(def forms
  ['(bit-xor (bit-shift-right (/ t 6) 11) (bit-and (bit-shift-right (/ t 6) 8) (* (bit-shift-right (/ t 6) (bit-or (bit-shift-right (/ t 18) 4) (bit-shift-left t 3))) t)))
   '(bit-or (bit-shift-right (bit-shift-right t (bit-and (bit-shift-right (/ t 12) 9) (* t t))) (bit-shift-right t 18)) (/ t 1000))
   '(bit-xor (bit-shift-right (* t (bit-shift-right 8 (int (* 3 (js/Math.sin (bit-and (* t 3) (int (/ t 329)))))))) (bit-and t 691)) (bit-shift-right (bit-and t 512) (int (* 5 (js/Math.sin (bit-and (* t 4) (int (/ t 753))))))))
   '(bit-or (bit-and (* t 6) (bit-or (bit-shift-right (bit-and t 512) (bit-and 7 (bit-shift-right t 12))) (/ t 127))) (bit-and (* t 4) (* (bit-shift-right t 6) 6)))
   '(bit-or t (bit-shift-right (bit-and t t) t))
   '(bit-or (bit-shift-right (bit-and (bit-shift-right t 3) (int t)) t) (bit-and t (mod (bit-shift-right t 10) 46)))
   '(bit-and (bit-shift-right (/ t 12) 2.5) (* (bit-shift-right (/ t 4) 4) t))
   '(bit-and (bit-shift-right (/ t 12) 2.5) (* (bit-shift-right (/ t 2) (bit-shift-right t 8)) t))
   '(bit-or (bit-or (bit-xor (bit-shift-left t 0) (bit-and (+ (bit-shift-left t 0) (bit-shift-right t 6)) (bit-shift-right t 12))) (bit-shift-right t (- 2 (bit-xor 1 (bit-xor (bit-shift-right (bit-and t 512) (int (* 3 (js/Math.sin (bit-and (* t 4) (bit-shift-right t 7)))))) (bit-shift-right (bit-and t 512) (int (* 4 (js/Math.sin (bit-and (* t 4) (/ t 512))))))))))) (bit-shift-right t 127))
   '(bit-and t (bit-shift-left (bit-shift-left t (bit-shift-right t 6)) 512))
   '(* t (js/Math.sin (+ t (mod (- t 0) 57))))
   '(bit-and (bit-shift-right (/ (/ t 3) 8) (bit-and 7 512)) (* (bit-shift-right (/ t (bit-and t (bit-shift-left t 3))) 0) t))
   '(* (* (mod 65278 (bit-and (bit-shift-left t 6) (bit-shift-right t 7))) t) 4)
   '(bit-xor (bit-or (bit-shift-right t 5) (bit-shift-left t 8)) (bit-and (* t 2) (bit-or (bit-shift-right t (bit-shift-right t 8)) (bit-shift-left t 2))))
   '(bit-and (bit-shift-right (bit-shift-left t (bit-and t t)) (bit-shift-left t (* t 7))) (bit-shift-left t (bit-or t (bit-or t 3))))
   '(+ (/ (* (* (bit-shift-right t 8) (- (bit-shift-right (bit-and t 16) 3) 83)) 128) 65) 63)
   '(bit-xor (bit-shift-right (/ t 6) 11) (bit-and (bit-shift-right (/ t 48) 8) (* (bit-shift-right (/ t 6) (bit-or (bit-shift-right (/ t (bit-shift-right (/ t 12) 9)) 4) (bit-shift-left t 3))) t)))
   '(bit-or (bit-or 10 (bit-and (bit-or (bit-shift-right (/ t 12) 3) (bit-shift-left t 4)) (bit-and (bit-shift-right (/ t 12) 2.5) (* (bit-shift-right (/ t 4) (int (/ t 6))) t)))) (bit-and (* t (bit-and t t)) (bit-or (bit-shift-right (/ (bit-and t t) 12) 66) (bit-shift-left t 2))))
   ])
